// Shared mock product data — used by API routes when DB is unavailable

export const MOCK_PRODUCTS = [
  {
    _id: '1',
    slug: 'rose-quartz-gua-sha',
    name: 'Rose Quartz Gua Sha',
    tagline: 'Sculpt. Depuff. Glow.',
    description:
      'Authentic rose quartz gua sha stone for facial lifting and lymphatic drainage. Cool to the touch, smooth on the skin. Use daily to reduce puffiness and define your jawline.',
    price: 2800,
    comparePrice: 3500,
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
      'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=600&q=80',
    ],
    category: 'self-care',
    tags: ['gua-sha', 'rose-quartz', 'facial', 'sculpt'],
    inStock: true,
    stockCount: 45,
    isFeatured: true,
    isNewDrop: true,
    isBestSeller: false,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    _id: '2',
    slug: 'led-glow-mirror',
    name: 'LED Glow Mirror',
    tagline: 'Studio lighting, anywhere.',
    description:
      'Compact LED vanity mirror with adjustable brightness and 10x magnification. USB rechargeable, perfect for flawless makeup on the go.',
    price: 4500,
    comparePrice: 5500,
    images: [
      'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600&q=80',
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80',
    ],
    category: 'self-care',
    tags: ['mirror', 'led', 'makeup', 'vanity'],
    inStock: true,
    stockCount: 23,
    isFeatured: true,
    isNewDrop: false,
    isBestSeller: true,
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-05'),
  },
  {
    _id: '3',
    slug: 'mini-chain-crossbody',
    name: 'Mini Chain Crossbody',
    tagline: 'Small bag. Big statement.',
    description:
      'Quilted mini crossbody bag with gold chain strap. Fits your phone, cards, and lip gloss. Goes from brunch to dinner without missing a beat.',
    price: 3200,
    comparePrice: null,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80',
      'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=600&q=80',
    ],
    category: 'accessories',
    tags: ['bag', 'crossbody', 'chain', 'quilted'],
    inStock: true,
    stockCount: 18,
    isFeatured: true,
    isNewDrop: true,
    isBestSeller: false,
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
  },
  {
    _id: '4',
    slug: 'jade-face-roller',
    name: 'Jade Face Roller',
    tagline: 'Roll away the stress.',
    description:
      'Dual-ended jade roller for facial massage and serum absorption. The larger end works on cheeks and forehead; the smaller end targets under-eyes.',
    price: 1800,
    comparePrice: 2200,
    images: [
      'https://images.unsplash.com/photo-1556228720-da8ead62f0f0?w=600&q=80',
      'https://images.unsplash.com/photo-1619451427882-6aeaded4a2b7?w=600&q=80',
    ],
    category: 'self-care',
    tags: ['jade', 'roller', 'facial', 'massage'],
    inStock: true,
    stockCount: 60,
    isFeatured: false,
    isNewDrop: false,
    isBestSeller: true,
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date('2025-01-08'),
  },
  {
    _id: '5',
    slug: 'acrylic-clutch',
    name: 'Acrylic Box Clutch',
    tagline: 'Art you carry.',
    description:
      'Clear acrylic clutch with gold hardware. A statement piece that turns heads. Spacious enough for your evening essentials.',
    price: 2500,
    comparePrice: null,
    images: [
      'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600&q=80',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80',
    ],
    category: 'accessories',
    tags: ['clutch', 'acrylic', 'transparent', 'evening'],
    inStock: true,
    stockCount: 12,
    isFeatured: false,
    isNewDrop: true,
    isBestSeller: false,
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-15'),
  },
  {
    _id: '6',
    slug: 'facial-steamer',
    name: 'USB Facial Steamer',
    tagline: 'Open up. Breathe in. Glow.',
    description:
      'Nano ionic facial steamer for deep pore cleansing and intense hydration. Use before your skincare routine to maximise absorption. Portable USB-powered design.',
    price: 3800,
    comparePrice: 4500,
    images: [
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80',
      'https://images.unsplash.com/photo-1614806687007-2215420d2e0e?w=600&q=80',
    ],
    category: 'self-care',
    tags: ['steamer', 'facial', 'pores', 'hydration'],
    inStock: true,
    stockCount: 35,
    isFeatured: false,
    isNewDrop: false,
    isBestSeller: false,
    createdAt: new Date('2025-01-12'),
    updatedAt: new Date('2025-01-12'),
  },
]
